visual/tutorials/__init__.py
from flask import Blueprint

mod = Blueprint('tutorials', __name__, url_prefix='/tutorials')

from . import views

visual/tutorials/views.py
from flask import render_template, request, redirect, flash, url_for, jsonify, abort, current_app, g
from flask_login import login_user, logout_user, login_required

from . import mod


@mod.route('/')
def index():
    return render_template('tutorials/index.html')


@mod.route('/how_it_works/')
def how_it_works():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/how_it_works.{}.html'.format(g.lang))


@mod.route('/system_requirements/')
def system_requirements():
    return render_template('tutorials/system_requirements.{}.{}.html'.format(current_app.config.get('JURISDICTION'), g.lang))


@mod.route('/quick_start_guide/')
def quick_start_guide():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/quick_start_guide.{}.html'.format(g.lang))


@mod.route('/setting_up_camera/')
def setting_up_camera():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/setting_up_camera.{}.html'.format(g.lang))


@mod.route('/preparing_geometry/')
def preparing_geometry():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/preparing_geometry.{}.html'.format(g.lang))


@mod.route('/setting_up_render/')
def setting_up_render():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/setting_up_render.{}.html'.format(g.lang))


@mod.route('/post_production/')
def post_production():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/post_production.{}.html'.format(g.lang))


@mod.route('/tour_editing_mode/')
def tour_editing_mode():
    return render_template('tutorials/tour_editing_mode.{}.html'.format(g.lang))


@mod.route('/uploading_assets/')
def uploading_assets():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/uploading_assets.{}.html'.format(g.lang))


@mod.route('/creating_interactive_objects/')
def creating_interactive_objects():
    return render_template('tutorials/creating_interactive_objects.{}.html'.format(g.lang))

@mod.route('/interactive_meshes/')
def interactive_meshes():
    return render_template('tutorials/interactive_meshes.{}.html'.format(g.lang))

@mod.route('/rendering_floor_plan/')
def rendering_floor_plan():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/rendering_floor_plan.{}.html'.format(g.lang))


@mod.route('/shades/')
def shades():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/shades.{}.html'.format(g.lang))


@mod.route('/releasing_tour/')
def releasing_tour():
    return render_template('tutorials/releasing_tour.{}.{}.html'.format(current_app.config.get('JURISDICTION'), g.lang))


@mod.route('/edit_assets/')
def edit_assets():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/edit_assets.{}.html'.format(g.lang))


@mod.route('/troubleshooting/')
def troubleshooting():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/troubleshooting.{}.html'.format(g.lang))


@mod.route('/installing_oculus/')
def installing_oculus():
    return render_template('tutorials/installing_oculus.{}.html'.format(g.lang))


@mod.route('/desktop_player/')
def desktop_player():
    return render_template('tutorials/desktop_player.{}.html'.format(g.lang))


@mod.route('/branding/')
def branding():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/branding.{}.html'.format(g.lang))


@mod.route('/model_replacement/')
def model_replacement():
    if current_app.config['JURISDICTION'] == 'ru':
        abort(404)
    return render_template('tutorials/model_replacement.{}.html'.format(g.lang))

visual/templates/tutorials/setting_up_camera.fr.html
{% extends 'base.html' %}
{% set page_title = _("Setting up camera") %}
{% set corpus_class = 'tutorials' %}
{% set background_head = '/static/public/img/tutorials/preparing-geometry/preview_big.jpg' %}

{% block head %}{% endblock %}

{% block content %}

    <div class="content-page">
        <div class="page-title page-title--textpage"{% if background_head %} style="background-image: url({{ background_head }});"{% endif %}>
            <div class="b-page__inner">
                <div class="page-title__inner">
                    <h1 class="h1 page-title__head">{{ page_title }}</h1>
                    <div class="page-title__tags tags">
                        <span class="tags__item tags__item--red">{{ _("must-read") }}</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="b-page__inner b-page__mrg">

            <div id="camera" class="b-anchor"></div>
            <div class="content-page__wrapper">
                <div id="short" class="b-anchor"></div>
                <div class="content-page__main">

                    <h2>Summary</h2>
                    <ol>
                        <li>Drag’n’drop <a href='/static/scripts3d/Biganto-UTL_VirtoasterCamTools_0.73.ms'>Virtoaster camera tool</a> to your scene to run the script</li>
                        <li>Press “Point”, place point helpers where you want to go. Maintain 1,5-3m distance between them</li>
                        <li>Set height of all created points at 1,5m above the floor</li>
                        <li>Press “Create camera”</li>
                        <li>Press “Select camera” and choose Virtoaster camera, then press “Apply Virtoaster render settings”</li>
                        <li>Proceed with <a href='{{ url_for('tutorials.setting_up_render') }}'>“Render settings”</a></li>
                    </ol>

                    <iframe style="width: 100%; height: 460px;" src="https://www.youtube.com/embed/STpTi3apqJ8"
                            frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen></iframe>

                    <div id="more" class="b-anchor"></div>
                    <h2>Full guide</h2>

                    <p>Virtoaster tours require two key assets to be made: sequence of 360 panoramic renders and a 3d model of the scene. Here we will show you how to start the rendering process, kicking off with camera setup.</p>
                    <p>To set up a camera, please download our <a href='/static/scripts3d/Biganto-UTL_VirtoasterCamTools_0.73.ms'>camera creation tool</a>. Open your scene and set viewport view to Top (hotkey T). Drag’n’drop camera creation tool to the viewport,  you will see the following interface:</p>
                    <p><img src="/static/public/img/tutorials/setting-camera/image_1.jpg" alt=""></p>
                    <p>Start with creating auxiliary Point objects. Press “Point” button in the script interface, press left mouse button to place points where you want to travel through the tour. Click right mouse button to stop.</p>
                    <p>Each point will correspond to a single render, so set points only where you would want to go. Try to place points evenly through the scene and only in places where it is physically possible to walk, e.g. do not place points on top of tables, beds, etc.</p>
                    <p><span class='warning'>Important:</span> do not place points too close to each other, it will be inconvenient, when travelling through the tour. We recommend to keep distance between the points at <strong>1,5-3 meters</strong>.</p>
                    <p>You will be able to travel between the points only if there is a clear line of sight. There should be no solid obstacles between neighboring points, like closed doors, curtains or screens.</p>
                    <p>To wrap it up, here are the main requirements:</p>
                    <ol>
                        <li>The distance between neighboring points should be no more than three meters.</li>
                        <li>Points, between which there will be a transition, must be in line of sight.</li>
                        <li>You should arrange  the points only where you can walk. For example, there should be no points above beds and tables.</li>
                        <li>You should distribute the points across the room evenly.</li>
                    </ol>
                    <p>See the example of correct placement below:</p>
                    <p><img src="/static/public/img/tutorials/setting-camera/image_5.jpg" alt="" width="720"></p>
                    <p>Next, select all created points and set their height at 1,5 meters from the floor (average human eye height). If there are some ladders or there are several floors in your scene you should take that into account and set height relative to the corresponding floor level.</p>
                    <p>Finally, select all your points and press “Create camera”. Animated camera will be created, with each point corresponding to a single frame.</p>
                    <p><span class='warning'>Important:</span> by default 3d max create points at a height of zero. Make sure you placed your points at proper height before creating the camera.</p>
                    <p>In addition to camera, extra geometry will be created for each point. It is used to determine the coordinates of the frame. These pieces of geometry are not renderable, so they will not impact your image.</p>
                    <p><img src="/static/public/img/tutorials/setting-camera/image_13.jpg" alt="" width="300"></p>
                    <p><span class='warning'>Important:</span> if, for any reasons you want to change the position of a point, please delete Camera and all auxiliary geometry first. Afterwards you should change point position and press Create camera again.</p>
                    <p><span class='warning'>Important:</span> if there are some animated objects in your scene, our tool will prompt the following message, asking you to delete them:</p>
                    <p><img src="/static/public/img/tutorials/setting-camera/image_14.jpg" alt=""></p>
                    <p>Animated objects will interfere with rendering through the animated camera, e.g. position of animated door will not align with 3d model on different frames of the tour. Thus, the only animation allowed in the scene is a camera created with our tool.</p>

                    <p>Press “Select camera” and choose Virtoaster camera, then press “Apply Virtoaster render settings”.  Script will automatically set the required settings for you and will return a message, to inform you about the changes it made: </p>
                    <p><img src="/static/public/img/tutorials/setting-camera/image_16.jpg" alt=""></p>
                    <p>These are the primary settings to create required panoramic images. Though you can start rendering already , we still suggest that you will check <a href='{{ url_for('tutorials.setting_up_render') }}'>“Render settings”</a> article first. </p>


                    <div id="optional" class="b-anchor"></div>
                    <h2>Optional step</h2>
                    <p>By default we determine coordinates of each frame from auxiliary geometry, created with our tool. However you can manually upload a coordinates of all your points, which is explained more thoroughly in our <a href='{{ url_for('tutorials.uploading_assets') }}'>“Uploading assets” guide</a>.</p>
                    <p>You should use our camera creation tool to create .txt file with the coordinates. Press “Select camera” and choose Virtoaster camera, then press “Create”. You will be asked to select a location where to store file with a coordinates on your PC.</p>
                    <p><img src="/static/public/img/tutorials/setting-camera/image_15.jpg" alt=""></p>

                </div>
                <aside class="content-page__side content-page__side--hide">

                    <nav class="side-menu sticky" data-top-spacing="96" data-res="lg">
                        <ul class="side-menu__list">
                            <li class="side-menu__item">
                                <a href="#short" class="side-menu__link link-scroll-to">Summary</a>
                            </li>
                            <li class="side-menu__item">
                                <a href="#more" class="side-menu__link link-scroll-to">Full guide</a>
                            </li>
                            <li class="side-menu__item">
                                <a href="#optional" class="side-menu__link link-scroll-to">Optional step</a>
                            </li>
                        </ul>
                    </nav>

                </aside>
            </div>
        </div>
    </div>

{% endblock %}

visual/templates/tutorials/setting_up_render.fr.html
{% extends 'base.html' %}
{% set page_title = _("Setting up 360 render") %}
{% set corpus_class = 'tutorials' %}
{% set background_head = '/static/public/img/tutorials/setting-up-render/preview_big.jpg' %}

{% block head %}{% endblock %}

{% block content %}

<div class="content-page">
    <div class="page-title page-title--textpage"{% if background_head %} style="background-image: url({{ background_head }});"{% endif %}>
        <div class="b-page__inner">
            <div class="page-title__inner">
                <h1 class="h1 page-title__head">{{ page_title }}</h1>
                <div class="page-title__tags tags">
                    <span class="tags__item tags__item--red">{{ _("must-read") }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="b-page__inner b-page__mrg">

        <div id="camera" class="b-anchor"></div>
        <div class="content-page__wrapper">
            <div id="short" class="b-anchor"></div>
            <div class="content-page__main">

                <h2>Summary</h2>
                <ol>
                    <li>Set render resolution and number of frames to render</li>
                    <li>Select camera type</li>
                    <li>Disable post processing effects</li>
                    <li>Proceed with 360 renders <a href='{{ url_for('tutorials.post_production') }}'>post processing</a></li>
                </ol>

                <div id="more" class="b-anchor"></div>
                <h2>Full guide</h2>

                <p><span class='warning'>Important:</span> you can set core render settings with Virtoaster Camera tool script. Nonetheless, it is required to manually disable post processing effects, if there are any (see the end of the article). </p>
                <p>Go to Render setup (F10), you need to specify the range of frames to render from the first to the last keyframe of the animated Virtoaster camera. Each frame corresponds to a single point in a tour.</p>
                <p>Set render resolution to 9216x1536px.</p>
                <p><img src="/static/public/img/tutorials/setting-up-render/image_9.jpg" alt="" width="360"></p>
                <p>Change the type of camera.</p>
                <p><b>For V-Ray:</b></p>
                <p>Open V-Ray tab. Set the camera type to Cube 6x1 (Render Setup/tab V-Ray/Scroll Camera/Type: Cube 6x1).</p>
                <p><img src="/static/public/img/tutorials/setting-up-render/image_10.jpg" alt="" width="360"></p>
                <p><b>For Corona:</b></p>
                <p>Select Virtoaster Camera. From the Modifier list  add “CoronaCameraMod” modifier. In CameraProjection scroll check the box at ProjectionType/Override. Select Cubemap in the dropdown list.</p>
                <p><img src="/static/public/img/tutorials/setting-up-render/image_11.jpg" alt="" width="360"></p>
                <p><span class='warning'>Important:</span> disable native Sharpening from Corona render. Disable any form of post processing effects, including vignetting, DoF, motion blur effects. This will result in visible seams between parts of 360 render! The only effect you may use when rendering cubemaps is Corona Bloom and Glare, and even than, use these effects with caution, as they may still slightly impact sides of cubemaps.</p>
                <p><img src="/static/public/img/tutorials/setting-up-render/image_12.jpg" alt=""></p>
                <p><span class='warning'>Important:</span> if you are using Corona 4.0 or newer, we recommend to disable High Quality image filter under System tab. High quality image filter sometimes causes visible seams on the Cubemaps. Please select "None" or "Tent" under image filter type.</p>
                <p>Select the folder you want to save your sequence and required render channels.</p>
                <p><span class='warning'>Important:</span> we do not recommend to use JPEG file format for render output and post processing. When uploading 360 renders to the tour, the engine will automatically convert and transform them into JPEG to show images in browser. Thus the images will be compressed twice: when rendering/adding post effects and when uploading to the tour!</p>
                <p>Once your renders are complete, you may proceed with <a href='{{ url_for('tutorials.post_production') }}'>image post production.</a></p>
            </div>

            <aside class="content-page__side content-page__side--hide">
                <nav class="side-menu sticky" data-top-spacing="96" data-res="lg">
                    <ul class="side-menu__list">
                        <li class="side-menu__item">
                            <a href="#short" class="side-menu__link link-scroll-to">Summary</a>
                        </li>
                        <li class="side-menu__item">
                            <a href="#more" class="side-menu__link link-scroll-to">Full guide</a>
                        </li>
                    </ul>
                </nav>
            </aside>
        </div>
    </div>
</div>

{% endblock %}

visual/templates/tutorials/shades.de.html
{% extends 'base.html' %}
{% set page_title = _("Shades") %}
{% set corpus_class = 'tutorials' %}
{% set background_head = '/static/public/img/tutorials/shades/shade_tile.jpg' %}

{% block head %}{% endblock %}

{% block content %}

<div class="content-page">
    <div class="page-title page-title--textpage"{% if background_head %} style="background-image: url({{ background_head }});"{% endif %}>
        <div class="b-page__inner">
            <div class="page-title__inner">
                <h1 class="h1 page-title__head">{{ page_title }}</h1>
                <div class="page-title__tags tags">
                    <span class="tags__item tags__item--green">{{ _("extra") }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="b-page__inner b-page__mrg">
        <div id="camera" class="b-anchor"></div>
        <div class="content-page__wrapper">
            <div id="short" class="b-anchor"></div>
            <div class="content-page__main">
                <p>So called “Shades” as of today is a very simple feature we intend to further improve and develop. It allows you to upload extra sets of images into the tour and switch between your original images and their “shades”. Using this feature you can add some extra flavor to your project, for example:</p>
                <ul>
                    <li>Show the same tour with day and night illumination</li>
                    <li>Show different finishing options, e.g. different floor tiles, paint schemes, etc.</li>
                    <li>Show different view from windows on different floors</li>
                </ul>
                <p>Tour and camera direction will remain unaffected when switching between different image sets, so load times are minimal. This means, however, that all sets of images should use the same 3d model.</p>
                <p>You can load as many sets of images as you want, for all points or only for some of them. All shades should have the same image index as their corresponding panoramas, e.g. Shade for point 4 should be named “shade_greenfloor004.png” and so on. They follow the same rules as regular images (resolution, image format, etc.).</p>
                <p>To add a set of shades into the tour simply enter Shades tab and press “Add shade”. You can also change the animation to be used when changing images inside the tour.</p>
                <p><img src="/static/public/img/tutorials/shades/shade_add.jpg" alt="" ></p>
                <p><span class='warning'>Important:</span> if you have shades only for some points in the tour, you will only see the switch in the points where you have shades uploaded. E.g. in the screenshot below you will be able to switch between shades only for points 6-11.</p>
                <p><img src="/static/public/img/tutorials/shades/shades_list.jpg" alt="" ></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

visual/templates/tutorials/uploading_assets.de.html
{% extends 'base.html' %}
{% set page_title = _("Uploading assets") %}
{% set corpus_class = 'tutorials' %}
{% set background_head = '/static/public/img/tutorials/uploading-assets/assets-uploading.jpeg' %}

{% block head %}{% endblock %}

{% block content %}

<div class="content-page">
    <div class="page-title page-title--textpage"{% if background_head %} style="background-image: url({{ background_head }});"{% endif %}>
        <div class="b-page__inner">
            <div class="page-title__inner">
                <h1 class="h1 page-title__head">{{ page_title }}</h1>
                <div class="page-title__tags tags">
                    <span class="tags__item tags__item--red">{{ _("must-read") }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="b-page__inner b-page__mrg">
        <div class="content-page__wrapper">

            <div id="more" class="b-anchor"></div>
            <div class="content-page__main">
                <h2>Creating new tour</h2>

                <p>To start creating a tour, press “Create tour” on the top of Virtoaster web page or enter existing folder and scroll down to the bottom of the tour list. You will enter asset uploading interface.</p>
                <p><img src="/static/public/img/tutorials/uploading-assets/image_1.png" alt="" /></p>
                <p>Any Virtoaster tour require three key assets. First, there are 360 panoramic renders. So far we only support the following images:</p>
                <ul>
                    <li>Cubemap 6x1 (12x1 for binocular renders) format</li>
                    <li>9216x1536 px. resolution (18432x1536 for binocular renders)</li>
                    <li>.jpg or .png image format (we recommend to upload only .png images to avoid double compression when using .jpg)</li>
                    <li>image file names should contain a sequential number in order to match renders with points in a tour (numbering should not have any breaks and file name should contain distinct number e.g. “Render_01.png”, “Render_02.png”, etc., names like “10001.png” can not be used.)</li>
                </ul>

                <div id="uploading_panoramas" class="b-anchor"></div>
                <h3>Uploading panoramas</h3>
                <p>If you followed our instructions for <a href='{{ url_for('tutorials.setting_up_camera') }}'>setting up camera</a> and managing <a href='{{ url_for('tutorials.setting_up_render') }}'>your render</a> settings carefully, you should already have required sequence of images. Select your render type and select files to upload - you will see the list of uploaded renders under the “Result” headline. From this list you can replace renders individually (hover with your mouse to the point and press “Delete central panorama”) or delete points altogether if necessary (“Delete point”).</p>
                <p>If some of uploaded files do not comply with the requirements, you will receive an error message in the bottom of the screen. Creating the tour will not be possible, unless every error has been addressed.</p>
                <p><img src="/static/public/img/tutorials/uploading-assets/image_2.jpg" width="360" alt="" /></p>
                <p>You may also want to upload binocular panoramas. Each binocular 12x1 panorama should have regular 6x1 equivalent.</p>

                <div id="uploading_3d_model" class="b-anchor"></div>
                <h3>Uploading 3d model</h3>
                <p>Next, upload 3d model of the scene. By default we expect to receive high poly .obj file, which will be optimized by our algorithm. You can follow our <a href='{{ url_for('tutorials.preparing_geometry') }}'>“Preparing geometry for Virtoaster”</a> guide to perform all necessary actions and export .obj file with proper settings.</p>
                <!--                <p><span class='warning'>Important:</span> your high poly 3d model will likely have a significant file size. To decrease file size to upload, please use zip archive (zip only!).</p>-->
                <p>Alternatively you can upload low poly model of the scene yourself. Model should not exceed 50 mb and should not exceed 200-300k polygons, otherwise you may face performance issues when loading and viewing the tour. Low poly model should not contain texture coordinates, model should be scaled in meters. Do not forget to uncheck “Optimize 3d model” flag when uploading.</p>
                <p>You can also uncheck "Create 3d panorama view" flag to prevent this process in our software. This
                    might save some time of tour processing if you do not want 3d panorama mode anyway. Note, however,
                    that you can not create 3d panorama separately from assembling the tour and, thus, it will be
                    unavailable to your until complete tour reassembly.
                </p>
                <p><span class='warning'>Important:</span> you can disable or enable 3d panorama mode anytime in tour options instead.</p>

                <div id="uploading_coordinates" class="b-anchor"></div>
                <h3>Uploading coordinates</h3>
                <p>Finally, there are coordinates of rendered panoramas. By default we recognize these coordinates from 3d model of the scene and auxiliary objects, created by our camera script. If you’ve followed instructions on how to set camera and uploaded high poly model of the scene you may skip this step.</p>
                <p>Otherwise, you should use our camera creation tool to create .txt file with the coordinates (more details in <a href='{{ url_for('tutorials.setting_up_camera') }}'>Setting up camera guide</a>). Upload these coordinates with file or copy-paste them into the text field. System will perform coordinates check and will show error messages if something is not in order.</p>
                <p>Once all the assets are uploaded and all error instances are resolved, you will be able to press “Create tour” in the bottom of the page. Your tour will be added to the queue, you will receive an email when it will be processed.</p>
                <p>When your tour will be complete, do not forget to change its status to “Published”. Follow <a href='{{ url_for('tutorials.releasing_tour') }}'>this guide</a> to access your tour, change status and share it.</p>
                <p>If you are unable to complete tour at the moment, you can always close the page and return to it later - this tour will be available from your user account. Unfinished tour are locked in “Loading” status inside parent folder. Press “Delete” from tour list if you do not intent to complete the tour.</p>
                <p><img src="/static/public/img/tutorials/uploading-assets/image_3.jpg" alt="" /></p>
            </div>

            <aside class="content-page__side content-page__side--hide">
                <nav class="side-menu sticky" data-top-spacing="96" data-res="lg">
                    <ul class="side-menu__list">
                        <li class="side-menu__item">
                            <a href="#more" class="side-menu__link link-scroll-to">Creating new tour</a>
                        </li>
                        <li class="side-menu__item">
                            <a href="#uploading_panoramas" class="side-menu__link link-scroll-to">Uploading panoramas</a>
                        </li>
                        <li class="side-menu__item">
                            <a href="#uploading_3d_model" class="side-menu__link link-scroll-to">Uploading 3d model</a>
                        </li>
                        <li class="side-menu__item">
                            <a href="#uploading_coordinates" class="side-menu__link link-scroll-to">Uploading coordinates</a>
                        </li>
                    </ul>
                </nav>
            </aside>
        </div>
    </div>
</div>

{% endblock %}