visual/models/support.py
from collections import OrderedDict

from sqlalchemy.dialects.postgresql import JSONB, ARRAY
from lagring import Asset

from visual.core import db, storage
from visual.util import now


class Issue(db.Model):
    __tablename__ = 'issues'

    STATUSES = OrderedDict([
        ('new', 'Новый'),
        ('process', 'В работе'),
        ('complete', 'Готово'),
        ('spam', 'Спам'),
    ])

    SUBJECTS = OrderedDict([
        ('tour', 'Проблемы с туром'),
        ('payment', 'Оплата и тарифы'),
        ('feedback', 'Обратная связь'),
        ('other', 'Другое'),
    ])

    id = db.Column(db.Integer(), primary_key=True)
    status = db.Column(db.Enum(*list(STATUSES.keys()), name='issue_status'), nullable=False, default='new', server_default='new')
    created = db.Column(db.DateTime(timezone=True), server_default=db.text('now()'), nullable=False)
    number = db.Column(db.String(255), nullable=False)

    subject = db.Column(db.Enum(*list(SUBJECTS.keys()), name='issue_subject'), nullable=False, server_default='other', default='other')
    tour_link = db.Column(db.String(2048))
    text = db.Column(db.Text())
    contact_email = db.Column(db.String(255))

    # Юзер, который создал тикет.
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='RESTRICT', onupdate='CASCADE'), index=True)

    user = db.relationship('User', foreign_keys=[user_id], backref='issues')

    def __repr__(self):
        return '<Issue %d:%s>' % (self.id, self.created)


class SoftwareVersion(db.Model, storage.Entity):
    __tablename__ = 'software_versions'
    __table_args__ = (db.Index('app_id', 'version'),)

    id = db.Column(db.Integer(), primary_key=True)
    created = db.Column(db.DateTime(timezone=True), server_default=db.text('now()'), nullable=False)
    created_by = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='SET NULL', onupdate='CASCADE'))
    app_id = db.Column(db.String(), nullable=False)
    version = db.Column(ARRAY(db.Integer(), zero_indexes=True))
    download_url = db.Column(db.Text())
    filename = db.Column(db.String())
    filesize = db.Column(db.Integer())

    file = Asset()
    creator = db.relationship('User', foreign_keys=[created_by])


class SoftwareDistributionKey(db.Model):
    __tablename__ = 'software_distribution_keys'

    id = db.Column(db.Integer(), primary_key=True)
    created = db.Column(db.DateTime(timezone=True), server_default=db.text('now()'), nullable=False)
    app_id = db.Column(db.CHAR(16), nullable=False, index=True)
    used = db.Column(db.DateTime(timezone=True), server_default=None, nullable=True)
    used_by = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='SET NULL', onupdate='CASCADE'), nullable=True)
    key = db.Column(db.Text(), nullable=False)

    __table_args__ = (db.Index('ix_app_id_key', 'app_id', 'key'),)

visual/admin/support/__init__.py
from . import support

__all__ = [
    'support'
]

visual/support/__init__.py
from flask import Blueprint

mod = Blueprint('support', __name__, url_prefix='/support')

from . import views

visual/support/views.py
from datetime import datetime

from flask import render_template, request, redirect, flash, url_for, jsonify, abort, current_app
from flask_login import current_user
from flask_babel import gettext

from visual.mail import send_email

from . import mod
from ..models import Issue
from ..core import db


@mod.route('/', methods=('GET', 'POST'))
def index():

    if request.method == 'POST':

        subject = request.json.get('subject')
        tour_link = request.json.get('tour', '').strip()
        issue = request.json.get('desc', '').strip()
        contact_email = request.json.get('email', '').strip()

        # валидация формы
        if subject not in ('tour', 'payment', 'feedback', 'other'):
            return jsonify({'errors': [gettext("Invalid subject.")]})
        if subject == 'tour' and tour_link == '':
            return jsonify({'errors': [gettext("Invalid tour link.")]})
        if issue == '':
            return jsonify({'errors': [gettext("Describe your issue.")]})
        if contact_email == '':
            return jsonify({'errors': [gettext("Invalid contact email.")]})

        # создание нового тикета
        first_issue = Issue.query.order_by(Issue.id.desc()).first()
        number = subject[0].upper() + datetime.now().strftime("%m%d") + str(getattr(first_issue, 'id', 0) + 1)

        issue = Issue(
            status='new',
            number=number,
            subject=subject,
            text=issue,
            contact_email=contact_email
        )
        if subject == 'tour':
            setattr(issue, 'tour_link', tour_link)
        if current_user.is_authenticated:
            issue.user_id = current_user.id

        db.session.add(issue)
        db.session.commit()

        # письмо на почтовый ящик техподдержки
        subject_email = 'Virtoaster support request #{}: {}. [{}]'.format(number, Issue.SUBJECTS.get(subject, subject),
                                                                          contact_email)
        send_email(
            subject_email,
            [current_app.config['SUPPORT_EMAIL']],
            template='admin/support/email/new_issue_created',
            issue=issue,
            user_id=issue.user_id
        )

        # письмо на почтовый ящик клиента
        subject_email = gettext('Virtoaster support request #%(number)s', number=number)
        if contact_email:
            send_email(
                subject_email,
                [contact_email],
                sender=current_app.config['SUPPORT_EMAIL'],
                template='front/email/new_issue_created',
                issue=issue
            )

        return jsonify({'status': 'ok'})

    return render_template('support/index.html')

visual/templates/support/index.html
{% extends 'base.html' %}
{% set page_ttl = _("Support") %}
{% set corpus_class = 'support' %}

{% block head %}{% endblock %}

{% block content %}
    <div class="page-title">
        <div class="b-page__inner page-title__inner page-title__inner--align-left">
            <h1 class="page-title__head background-image-title h1">{{ page_ttl }}</h1>
        </div>
    </div>
    <div class="b-page__inner b-page__mrg support-page">

        <section class="support-page__form">
            {% if config.JURISDICTION == 'ru' %}
            <p class="support-form__intro">Добро пожаловать в службу поддержки Biganto! Для получения технической поддержки, свяжитесь с нами с помощью email или Telegram.</p>
            {% endif %}
            {% if config.JURISDICTION == 'world' %}
            <form action="{{ url_for('support.index') }}" class="support-form form-modal" type="post">
                <p class="support-form__intro">{{ _("Welcome to Virtoaster support! Please, complete the form and we will address your request as soon as possible.") }}</p>
                <div class="support-form__answer"></div>
                <div class="support-form__inner">
                    <div class="form-modal__section">
                        <div class="form-modal__label">{{ _("Subject") }}</div>
                        <div class="form-modal__field">
                            <div class="big-select">
                                <select name="subject" class="big-select__input support-form__subject" tabindex="0">
                                    <option value=""></option>
                                    <option value="tour">{{ _("Issue with created tour") }}</option>
                                    <option value="payment">{{ _("Issue with payment/tariff, etc.") }}</option>
                                    <option value="feedback">{{ _("Request feature/provide feedback") }}</option>
                                    <option value="other">{{ _("Other") }}</option>
                                </select>
                                <svg viewBox="0 0 9 8" class="big-select__icon" width="9" height="8"><use xlink:href="/static/public/img/icons.svg?{{ config.get('RELEASE_VERSION') }}#triangle-down" /></svg>
                            </div>
                        </div>
                    </div>
                    <div class="support-form__block support-form__block--tour">
                        <div class="form-modal__section">
                            <div class="form-modal__label">{{ _("Link to the tour") }}</div>
                            <div class="form-modal__field">
                                <input type="text" class="big-input support-form__tour" value="" placeholder="" name="tour_link" tabindex="0">
                            </div>
                            <div class="form-modal__comment">{{ _("Please, provide a link to the tour you having trouble with.") }}</div>
                        </div>
                        <div class="form-modal__section">
                            <div class="form-modal__field">
                                <label class="big-checkbox">
                                    <input type="checkbox" class="big-checkbox__input support-form__helpless" name="type" value="1" tabindex="0">
                                    <span class="big-checkbox__checkmark"></span>
                                    <span class="big-checkbox__label">
                                        <span>{{ _("Have you tried to solve the issue using <a href='%(url)s' target='_blank'>“Troubleshooting”</a> guide?", url=url_for('tutorials.troubleshooting')) }}</span>
                                    </span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="support-form__block support-form__block--desc">
                        <div class="form-modal__section">
                            <div class="form-modal__label">{{ _("Message:") }}</div>
                            <div class="form-modal__field">
                                <textarea class="big-input support-form__desc" value="" placeholder="" name="issue" tabindex="0"></textarea>
                            </div>
                        </div>
                        <div class="form-modal__section">
                            <div class="form-modal__label">{{ _("Contact email") }}</div>
                            <div class="form-modal__field">
                                <input type="email" class="big-input support-form__email" value="{{ current_user.email if current_user.is_authenticated else '' }}" placeholder="" name="email" tabindex="0">
                            </div>
                        </div>
                        <input type="hidden" value="" name="user_id" class="support-form__user">
                    </div>
                    <div class="support-form__submit">
                        <button type="submit" class="button fill blue support-form__button" tabindex="0" disabled>{{ _("Submit") }}</button>
                    </div>
                </div>
                <div class="support-form__success">{{ _("We are working on your request! Please, be patient, we will contact you soon.") }}</div>
                <div class="support-form__error"></div>
            </form>
            {% endif %}
        </section>
        <div class="support-page__contacts">
            <section class="support-contacts">
                <div class="support-contacts__item">
                    <a href="mailto:{{ config['SUPPORT_EMAIL'] }}" class="support-contacts__link">
                        <div class="support-contacts__icon">
                            <svg viewBox="0 0 100.72 106.68" class="icon__svg" width="50" height="50"><use xlink:href="/static/public/img/icons.svg?{{ config.get('RELEASE_VERSION') }}#email"></svg>
                        </div>
                        <div class="support-contacts__label">
                            <span class="support-contacts__name">{{ _("E-mail") }}</span>
                            <span class="support-contacts__value">{{ config['SUPPORT_EMAIL'] }}</span>
                        </div>
                    </a>
                </div>
                <div class="support-contacts__item">
                    <a href="https://t.me/{{ config['SUPPORT_TELEGRAM'] }}" class="support-contacts__link" target="_blank">
                        <div class="support-contacts__icon">
                            <svg viewBox="0 0 15 12.57" class="icon__svg" width="50" height="50"><use xlink:href="/static/public/img/icons.svg?{{ config.get('RELEASE_VERSION') }}#telega"></svg>
                        </div>
                        <div class="support-contacts__label">
                            <span class="support-contacts__name">{{ _("Telegram") }}</span>
                            <span class="support-contacts__value">@{{ config['SUPPORT_TELEGRAM'] }}</span>
                        </div>
                    </a>
                </div>
            </section>
        </div>

    </div>
{% endblock %}